import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

async function runSandbox(runId: string) {
  const runDir = path.join(process.cwd(), 'data', 'runs', runId);
  const scriptPath = path.join(runDir, 'generate_assets.py');
  const assetDir = path.join(runDir, 'assets');

  if (!fs.existsSync(scriptPath)) {
    throw new Error(`Script not found at ${scriptPath}`);
  }

  if (!fs.existsSync(assetDir)) fs.mkdirSync(assetDir, { recursive: true });

  console.log(`Executing ${scriptPath} in sandbox...`);

  try {
    // Run the python script in the run directory context
    // We'll move to the asset directory so the script saves files there
    execSync(`cd ${assetDir} && python3 ${scriptPath}`, { stdio: 'inherit' });

    // Update run.json with the new asset paths
    const runJsonPath = path.join(runDir, 'run.json');
    const runData = JSON.parse(fs.readFileSync(runJsonPath, 'utf8'));
    
    const files = fs.readdirSync(assetDir);
    const assetFilePaths: Record<string, string> = {};
    for (const file of files) {
      if (file.endsWith('.png')) {
        const key = file.replace('.png', '');
        assetFilePaths[key] = `/data/runs/${runId}/assets/${file}`;
      }
    }

    runData.asset_file_paths = assetFilePaths;
    runData.status = 'complete';
    runData.generation_notes += '\nAssets successfully generated by sandbox runner.';

    fs.writeFileSync(runJsonPath, JSON.stringify(runData, null, 2));
    console.log(`Updated manifest for ${runId}. ${Object.keys(assetFilePaths).length} assets found.`);

  } catch (err: any) {
    console.error(`Execution failed for ${runId}:`, err.message);
    const runJsonPath = path.join(runDir, 'run.json');
    const runData = JSON.parse(fs.readFileSync(runJsonPath, 'utf8'));
    runData.status = 'error';
    runData.generation_notes += `\nError during execution: ${err.message}`;
    fs.writeFileSync(runJsonPath, JSON.stringify(runData, null, 2));
  }
}

const targetRun = process.argv[2];
if (!targetRun) {
  console.error("Usage: ts-node scripts/sandbox-runner.ts <run-id>");
  process.exit(1);
}
runSandbox(targetRun).catch(console.error);
